FROM node:20
WORKDIR /usr/src/app

# Copy package.json from the root directory
COPY package*.json ./

RUN mkdir ./packages
RUN mkdir ./packages/shared
RUN mkdir ./packages/frontend

COPY packages/frontend/package.json ./packages/frontend
COPY packages/frontend/tsconfig.json ./packages/frontend
COPY packages/frontend/tsconfig.app.json ./packages/frontend
COPY packages/frontend/angular.json ./packages/frontend

WORKDIR /usr/src/app/packages/frontend

RUN npm install

WORKDIR /usr/src/app/

COPY packages/shared/models ./packages/shared/models
COPY packages/frontend/src ./packages/frontend/src
COPY packages/frontend/public ./packages/frontend/public

WORKDIR /usr/src/app/packages/frontend
# make the ARG flobal for docker
ARG environment

# Build the application
RUN npm run build

FROM nginx

# Install certbot to generate certificates
RUN apt update
RUN apt install certbot -y python3-certbot-nginx
RUN apt install -y vim

WORKDIR /usr/src/app

# Certificates for nginx
COPY nginx/initial-letsencrypt-files/ /etc/letsencrypt/

COPY nginx/conf/production/conf.d/default.conf /etc/nginx/conf.d/
COPY --from=0 /usr/src/app/packages/frontend/dist/frontend/browser /var/www/frontend/
