FROM node:20

RUN apt-get update
RUN apt-get install -y ca-certificates fonts-liberation gconf-service libappindicator1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 \
                       libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 \
                       libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 \
                       libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
                       libxi6 libxrandr2 libxrender1 libxss1 libxtst6 wget zip rsync

WORKDIR /usr/src/app

# Copy package.json and package-lock.json from the backend directory
#COPY package*.json ./
COPY packages/backend/package*.json ./

# Make directories for backend and shared project
RUN mkdir ./packages
RUN mkdir ./packages/shared
RUN mkdir ./packages/backend

# Copy files required for 'npm install'
COPY packages/backend/package.json ./packages/backend/
COPY packages/backend/tsconfig.json ./packages/backend/

RUN npm install

# copy all code
COPY packages/shared/models ./packages/shared/src

COPY packages/backend/src ./packages/backend/src
COPY packages/backend/config ./packages/backend/config

WORKDIR /usr/src/app/packages/backend

