# Use Node.js base image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY packages/backend/package*.json ./

# Make directories for backend and shared project
RUN mkdir ./packages
RUN mkdir ./packages/shared
RUN mkdir ./packages/backend

# Copy files required for 'npm install'
COPY packages/backend/package.json ./packages/backend/
COPY packages/backend/tsconfig.json ./packages/backend/

RUN npm install

RUN npm run build

# copy all code
COPY packages/shared/models ./packages/shared/src

COPY packages/backend/src ./packages/backend/src
COPY packages/backend/config ./packages/backend/config

WORKDIR /usr/src/app/packages/backend

# Expose the port
EXPOSE 4002

# Start the application
CMD ["npm", "run", "start-development"]
