export interface IStockData {
    id?: number;  // optional because it may be auto-generated by Sequelize
    datePublished: Date;
    priceLastTransaction: number;
    minPrice: number;
    maxPrice: number;
    averagePrice: number;
    promotionPercentage: number;
    quantity: number;
    turnoverBESTDenar: number;
    totalTurnoverDenars: number;
    stockSymbol: string;
    createdAt: Date;
    updatedAt: Date;
}
